In [19]:
import pandas as pd
df= pd.read_csv('test1.csv')
df.drop(['Unnamed: 0'],axis=1)
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
import pandas as pd
df['amneties'].fillna('', inplace=True)
def custom_tokenizer(text):
    tokens = word_tokenize(text)
    return tokens
vectorizer = TfidfVectorizer(tokenizer=custom_tokenizer)
amenities_tfidf = vectorizer.fit_transform(df['amneties'])
amenities_df = pd.DataFrame(amenities_tfidf.toarray(), columns=vectorizer.get_feature_names())
df_processed = pd.concat([df, amenities_df], axis=1)
df_processed = df_processed.drop(columns=['Unnamed: 0','amneties'],axis=1)
df_processed.to_csv('preprocessedoyo.csv',index=False)
df=pd.read_csv('preprocessedoyo.csv')

df


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hashif\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
C:\Users\Hashif\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


price  distance  ratings        ac      area  attached    backup  \
0   1199.000000       5.1  4.60000  0.128555  0.417493       0.0  0.168691   
1    799.000000       5.0  4.00000  0.157117  0.000000       0.0  0.206171   
2    747.000000       4.0  3.36129  0.255487  0.000000       0.0  0.335252   
3    576.000000       8.8  3.10000  0.249882  0.000000       0.0  0.327898   
4    699.000000       1.7  2.30000  0.255487  0.000000       0.0  0.335252   
..          ...       ...      ...       ...       ...       ...       ...   
95  1153.977778       5.1  4.70000  0.307017  0.000000       0.0  0.402870   
96  1153.977778       8.2  4.10000  0.221461  0.000000       0.0  0.000000   
97  1153.977778       5.7  4.30000  0.107249  0.000000       0.0  0.140733   
98  1153.977778       1.6  2.00000  0.307017  0.000000       0.0  0.402870   
99  1153.977778       3.1  3.40000  0.255487  0.000000       0.0  0.335252   

    bathroom       bed  breakfast  ...     queen  reception  restaurant  \
0        0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
1        0.0  0.469837   0.000000  ...  0.544623        0.0         0.0   
2        0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
3        0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
4        0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
..       ...       ...        ...  ...       ...        ...         ...   
95       0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
96       0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
97       0.0  0.000000   0.517525  ...  0.000000        0.0         0.0   
98       0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   
99       0.0  0.000000   0.000000  ...  0.000000        0.0         0.0   

     seating     sized  speed        tv  wardrobe  washroom      wifi  
0   0.417493  0.000000    0.0  0.129835       0.0       0.0  0.160229  
1   0.000000  0.469837    0.0  0.158681       0.0       0.0  0.195829  
2   0.000000  0.000000    0.0  0.258030       0.0       0.0  0.318435  
3   0.000000  0.000000    0.0  0.252369       0.0       0.0  0.000000  
4   0.000000  0.000000    0.0  0.258030       0.0       0.0  0.318435  
..       ...       ...    ...       ...       ...       ...       ...  
95  0.000000  0.000000    0.0  0.310073       0.0       0.0  0.382662  
96  0.000000  0.000000    0.0  0.223666       0.0       0.0  0.276026  
97  0.000000  0.000000    0.0  0.108316       0.0       0.0  0.133674  
98  0.000000  0.000000    0.0  0.310073       0.0       0.0  0.382662  
99  0.000000  0.000000    0.0  0.258030       0.0       0.0  0.318435  

[100 rows x 48 columns]

In [25]:
from sklearn.feature_selection import SelectKBest, chi2

k = 2
df_temp = df.drop('price', axis=1)
selector = SelectKBest(score_func=chi2, k=k)
df['price']=df['price'].astype('int')
selected_features = selector.fit_transform(df_temp, df['price'])
print(df['price'].dtype)
feature_names = df_temp.columns[selector.get_support()]
df_selected = pd.DataFrame(selected_features, columns=feature_names)
df_selected['price'] = df_processed['price']
print(df_selected)

int32
    bathroom  reception        price
0        0.0        0.0  1199.000000
1        0.0        0.0   799.000000
2        0.0        0.0   747.000000
3        0.0        0.0   576.000000
4        0.0        0.0   699.000000
..       ...        ...          ...
95       0.0        0.0  1153.977778
96       0.0        0.0  1153.977778
97       0.0        0.0  1153.977778
98       0.0        0.0  1153.977778
99       0.0        0.0  1153.977778

[100 rows x 3 columns]


dtype('float64')

In [11]:
import pandas as pd
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
nltk.download('averaged_perceptron_tagger')
df = pd.read_csv('test.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df['amenities'].fillna('', inplace=True)
stemmer = PorterStemmer()
def custom_tokenizer(text):
    tokens = word_tokenize(text)
    pos_tags = pos_tag(tokens)  # Perform POS tagging
    filtered_tokens = [token for token, pos in pos_tags if pos not in ['RB', 'JJ', 'VB']]  # Filter out adverbs, adjectives, and verbs
    return filtered_tokens
nltk.download('stopwords')
stopwords_list = set(stopwords.words('english'))
vectorizer = TfidfVectorizer(tokenizer=custom_tokenizer, stop_words=stopwords_list)
amenities_tfidf = vectorizer.fit_transform(df['amenities'])
amenities_df = pd.DataFrame(amenities_tfidf.toarray(), columns=vectorizer.get_feature_names())
from sklearn.preprocessing import LabelEncoder
# Perform label encoding for categorical features
categorical_features = ['type', 'location']
label_encoder = LabelEncoder()
label_encoders={}
for feature in categorical_features:
    df[feature] = label_encoder.fit_transform(df[feature])
    label_encoders[feature] = label_encoder
df_processed = pd.concat([df, amenities_df], axis=1)

df_processed.drop(columns=['amenities','distance'], axis=1, inplace=True)
df_processed.to_csv('preprocessed.csv', index=False)
df_processed = pd.read_csv('preprocessed.csv')
df_processed
column_names = df_processed.columns.tolist()

# Print the column names
print(column_names)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Hashif\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hashif\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
C:\Users\Hashif\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", 'could', 'might', 'must', 'need', 'sha', 'wo', 'would'] not in stop_words.
  warnings.warn(


['price', 'location', 'ratings', 'type', '(', ')', '2', 'air', 'airport', 'bar', 'breakfast', 'centre', 'closed', 'conditioning', 'desk', 'facilities', 'family', 'fitness', 'front', 'garden', 'guests', 'housekeeping', 'laundry', 'maker', 'non-smoking', 'parking', 'pool', 'pools', 'restaurant', 'room', 'rooms', 'service', 'shuttle', 'site', 'spa', 'superb', 'swimming', 'tea/coffee', 'terrace', 'wellness', 'wifi']


C:\Users\Hashif\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [3]:
import pandas as pd
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from nltk import pos_tag
import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
nltk.download('averaged_perceptron_tagger')
df = pd.read_csv('test.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df['amenities'].fillna('', inplace=True)
def custom_tokenizer(text):
    tokens = word_tokenize(text)
    pos_tags = pos_tag(tokens)
    filtered_tokens = [token for token, pos in pos_tags if pos not in ['RB', 'JJ', 'VB']]  # Filter out adverbs, adjectives, and verbs
    return filtered_tokens
nltk.download('stopwords')
stopwords_list = set(stopwords.words('english'))
custom_stopwords = ['(',')','2'] 
all_stopwords = stopwords_list.union(custom_stopwords)
vectorizer = TfidfVectorizer(tokenizer=custom_tokenizer,ngram_range=(1, 2), stop_words=all_stopwords)
amenities_tfidf = vectorizer.fit_transform(df['amenities'])
amenities_df = pd.DataFrame(amenities_tfidf.toarray(), columns=vectorizer.get_feature_names())

from sklearn.preprocessing import LabelEncoder
categorical_features = ['type', 'location']
label_encoder = LabelEncoder()
label_encoders={}
for feature in categorical_features:
    df[feature] = label_encoder.fit_transform(df[feature])
    label_encoders[feature] = label_encoder
df_processed = pd.concat([df, amenities_df], axis=1)

df_processed.drop(columns=['amenities','distance'], axis=1, inplace=True)
df_processed.to_csv('preprocessed.csv', index=False)
df_processed = pd.read_csv('preprocessed.csv')
df_processed
column_names = df_processed.columns.tolist()

# Print the column names
print(column_names)

[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 11001] getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
C:\Users\Hashif\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", 'could', 'might', 'must', 'need', 'sha', 'wo', 'would'] not in stop_words.
  warnings.warn(


['price', 'location', 'ratings', 'type', 'air', 'air conditioning', 'airport', 'airport family', 'airport room', 'airport shuttle', 'airport spa', 'airport wifi', 'bar', 'bar air', 'bar breakfast', 'bar closed', 'bar housekeeping', 'bar superb', 'bar tea/coffee', 'breakfast', 'centre', 'centre closed', 'centre facilities', 'centre front', 'centre room', 'centre rooms', 'centre spa', 'centre tea/coffee', 'centre wifi', 'closed', 'closed breakfast', 'closed non-smoking', 'closed parking', 'closed room', 'conditioning', 'conditioning breakfast', 'conditioning superb', 'conditioning tea/coffee', 'desk', 'desk air', 'desk bar', 'desk breakfast', 'desk garden', 'desk housekeeping', 'desk laundry', 'desk tea/coffee', 'desk terrace', 'facilities', 'facilities guests', 'family', 'family rooms', 'fitness', 'fitness centre', 'fitness housekeeping', 'front', 'front desk', 'garden', 'garden air', 'garden bar', 'garden breakfast', 'garden housekeeping', 'garden laundry', 'garden tea/coffee', 'guests

C:\Users\Hashif\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [19]:
X = df_processed.drop('price', axis=1)
y = df_processed['price']
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SelectKBest, mutual_info_regression
k = 20
selector = SelectKBest(score_func=mutual_info_regression, k=k)
X_new = selector.fit_transform(X, y)
feature_names = X.columns[selector.get_support()]
df_selected = pd.DataFrame(X_new, columns=feature_names)
df_selected['price'] = y
print(df_selected)

     location  ratings  type  24-hour front  air conditioning  \
0        22.0      8.5  15.0       0.171027          0.224802   
1        21.0      8.3  90.0       0.000000          0.000000   
2        28.0      8.4  90.0       0.132391          0.000000   
3        28.0      7.8  14.0       0.000000          0.000000   
4        21.0      8.0  93.0       0.000000          0.000000   
..        ...      ...   ...            ...               ...   
730      28.0      1.0   9.0       0.199160          0.000000   
731       6.0      4.6   9.0       0.000000          0.000000   
732      18.0      1.0   9.0       0.000000          0.257179   
733      18.0      2.3   9.0       0.242209          0.000000   
734      24.0      4.0   9.0       0.000000          0.226619   

     centre non-smoking  daily housekeeping  family rooms  fitness centre  \
0              0.000000            0.000000      0.199289        0.000000   
1              0.268677            0.000000      0.000000        

In [20]:
X = df_processed.drop('price', axis=1)
y = df_processed['price']
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SelectKBest, mutual_info_regression
model = LinearRegression()
k = 5
rfe = RFE(estimator=model, n_features_to_select=k)
X_rfe = rfe.fit_transform(X, y)
feature_names = X.columns[rfe.support_]


df_selected = pd.DataFrame(X_rfe, columns=feature_names)
df_selected['price'] = y

print(df_selected)







     2 swimming  centre tea/coffee  pools airport  pools free  pools spa  \
0           0.0                0.0            0.0         0.0        0.0   
1           0.0                0.0            0.0         0.0        0.0   
2           0.0                0.0            0.0         0.0        0.0   
3           0.0                0.0            0.0         0.0        0.0   
4           0.0                0.0            0.0         0.0        0.0   
..          ...                ...            ...         ...        ...   
730         0.0                0.0            0.0         0.0        0.0   
731         0.0                0.0            0.0         0.0        0.0   
732         0.0                0.0            0.0         0.0        0.0   
733         0.0                0.0            0.0         0.0        0.0   
734         0.0                0.0            0.0         0.0        0.0   

     price  
0      900  
1     4125  
2     1259  
3      920  
4     2000  
..     ..

In [21]:
from sklearn.feature_selection import SelectKBest, chi2

k = 3
df_temp = df_processed.drop('price', axis=1)

selector = SelectKBest(score_func=chi2, k=k)
selected_features = selector.fit_transform(df_temp, df_processed['price'])
feature_names = df_temp.columns[selector.get_support()]
df_selected = pd.DataFrame(selected_features, columns=feature_names)
df_selected['price'] = df_processed['price']
print(df_selected)

     location  type  service laundry  price
0        22.0  15.0              0.0    900
1        21.0  90.0              0.0   4125
2        28.0  90.0              0.0   1259
3        28.0  14.0              0.0    920
4        21.0  93.0              0.0   2000
..        ...   ...              ...    ...
730      28.0   9.0              0.0    489
731       6.0   9.0              0.0    929
732      18.0   9.0              0.0    970
733      18.0   9.0              0.0    487
734      24.0   9.0              0.0    437

[735 rows x 4 columns]


In [ ]:
column_names = df['type'].tolist()

# Print the column names
print(column_names)

In [ ]:
real_value = label_encoder.inverse_transform(df['location'])[2]
real_value

In [ ]:
column_name = 'type'
label = df[''].mode()
label_encoder = label_encoders[column_name]
real_value = label_encoder.inverse_transform([label])[0]

real_value

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Read the dataset
df = pd.read_csv('test.csv')
df = df.drop(['Unnamed: 0'], axis=1)

# Perform label encoding for categorical features
categorical_features = ['type', 'location', 'amenities']
label_encoders = {}

for feature in categorical_features:
    label_encoder = LabelEncoder()
    df[feature] = label_encoder.fit_transform(df[feature])
    label_encoders[feature] = label_encoder

# Save the preprocessed data
df.to_csv('preprocessed.csv', index=False)

# Read the preprocessed data
df = pd.read_csv('preprocessed.csv')

# Retrieve the real value of a specified label in a column
column_name = 'location'
label = 2
label_encoder = label_encoders[column_name]
real_value = label_encoder.inverse_transform([label])[0]

print(f"Real value of column '{column_name}' with label {label}: {real_value}")


In [8]:
import pandas as pd
df = pd.read_csv("preprocessed.csv")
zero_counts = {}
for column in df.columns:
    zero_count = (df[column] == 0).sum()
    zero_counts[column] = zero_count
lst=[]
for column in df.columns:
    minz= zero_counts[column]
    for columns in df.columns:
        if column in columns:
            if zero_counts[columns]<=minz:
                minz= zero_counts[columns]
            else:
                lst.append(columns)
                
df_dropped = df.drop(columns=lst)
df_dropped.to_csv('ndf.csv',index= True)
            



In [34]:
print(df.head())

   price  location  distance  \
0    900        22       NaN   
1   4125        21       NaN   
2   1259        28       NaN   
3    920        28       NaN   
4   2000        21       NaN   

                                           amenities  ratings  type  
0  Room service Non-smoking rooms Free WiFi Free ...      8.5    15  
1  Airport shuttle Room service Fitness centre No...      8.3    90  
2  Airport shuttle Room service Non-smoking rooms...      8.4    90  
3  Room service Free parking Spa and wellness cen...      7.8    14  
4  Airport shuttle Spa and wellness centre Room s...      8.0    93  


In [42]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('test.csv')
df['amenities'].fillna('', inplace=True)
df.drop(columns=['Unnamed: 0', 'distance'], axis=1, inplace=True)
# Preprocess the text data
text_data = df['amenities'].values
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)
sequences = tokenizer.texts_to_sequences(text_data)
max_sequence_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)
print(padded_sequences)

# Split the data into training and testing sets
labels = df['price'].values
train_size = int(0.8 * len(padded_sequences))
train_sequences = padded_sequences[:train_size]
train_labels = labels[:train_size]
test_sequences = padded_sequences[train_size:]
test_labels = labels[train_size:]

# Build and train the LSTM model
embedding_dim = 100
lstm_units = 64
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=embedding_dim, input_length=max_sequence_length))
model.add(LSTM(units=lstm_units))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_sequences, train_labels, epochs=10, batch_size=32, validation_data=(test_sequences, test_labels))

# Evaluate the model
loss, accuracy = model.evaluate(test_sequences, test_labels)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")


[[ 0  0  0 ... 23 15 16]
 [ 0  0  0 ... 41 34 12]
 [ 0  0  0 ... 41 34 12]
 ...
 [ 0  0  0 ... 20 15 16]
 [ 0  0  0 ...  8 19 20]
 [ 0  0  0 ... 20 15 16]]
Epoch 1/10
19/19 [==============================] - 2s 32ms/step - loss: -2748.6187 - accuracy: 0.0000e+00 - val_loss: -6659.8535 - val_accuracy: 0.0000e+00
Epoch 2/10
19/19 [==============================] - 0s 13ms/step - loss: -18491.5801 - accuracy: 0.0000e+00 - val_loss: -12507.5830 - val_accuracy: 0.0000e+00
Epoch 3/10
19/19 [==============================] - 0s 12ms/step - loss: -26599.2461 - accuracy: 0.0000e+00 - val_loss: -15697.3438 - val_accuracy: 0.0000e+00
Epoch 4/10
19/19 [==============================] - 0s 13ms/step - loss: -31799.6230 - accuracy: 0.0000e+00 - val_loss: -18129.0332 - val_accuracy: 0.0000e+00
Epoch 5/10
19/19 [==============================] - 0s 13ms/step - loss: -36193.6875 - accuracy: 0.0000e+00 - val_loss: -20302.8438 - val_accuracy: 0.0000e+00
Epoch 6/10
19/19 [==============================] -